package baymax.ui;

import java.util.Scanner;

/**
 * Handles console input and output for Baymax.
 */
public class Ui {
    private static final String SEPARATOR =
            "____________________________________________________________";
    private final Scanner scanner = new Scanner(System.in);

    /**
     * Checks whether another command is available.
     *
     * @return true if another command can be read
     */
    public boolean hasNextCommand() {
        return scanner.hasNextLine();
    }

    /**
     * Reads one command from the user.
     *
     * @return the user's command
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Closes the input scanner.
     */
    public void close() {
        scanner.close();
    }

    /**
     * Displays Baymax's welcome message.
     */
    public void showWelcome() {
        System.out.print("""
            ____________________________________________________________
            BBBB   aaa   y   y  m     m   aaa   x   x
            B   B a   a  y   y  mm   mm  a   a  x   x
            B   B a   a   y y   m m m m  a   a   x x
            BBBB  aaaaa    y    m  m  m  aaaaa    x
            B   B a   a    y    m     m  a   a   x x
            B   B a   a    y    m     m  a   a  x   x
            BBBB  a   a    y    m     m  a   a  x   x
            Hello. I am Baymax, your personal task companion.
            I am here to keep your tasks healthy and organized.
            How may I assist you?
            ____________________________________________________________
            """);
    }

    /**
     * Displays a separator between commands.
     */
    public void showSeparator() {
        System.out.println(SEPARATOR);
    }

    /**
     * Displays a response generated by Baymax.
     *
     * @param response the response text to display
     */
    public void showResponse(String response) {
        System.out.println(response);
    }

    /**
     * Displays a storage error.
     */
    public void showSaveError() {
        System.out.println(
                "I have some concerns. I cannot save your care plan right now.");
    }
}
